### ISSUE TITLE
Change Kyma Synchronization from SKR and KCP to SuperSet of Modules

### ISSUE THREAD

**Issue by jakobmoellersap** [kyma-project/kyma-operator#95]
The resulting set of all modules should consist of all modules from SKR and KCP combined. 

Trade-Off: Removal of a module requires removal from both KCP and SKR. Adding A module requires only one place for the change

AC:
- [x] Make sure that KCP Changes are not overwritten by Spec Changes of SKR Changes
- [x] Make sure that SKR Changes are not overritten by Spec Changes of KCP
- [x] Make sure that SKR + KCP Modules (without Duplicates) = Total Set of Modules to be installed

Developer Notes:
- It might be necessary to introduce a refactoring of the conditions so that the deletion of removed modules is handled properly
- The merging of the two CRs from SKR and KCP requires us to continously maintain a "virtual" set of modules that Kyma is actually installing, thus needing a small refactor of the sync logic
- The Sync that is happening needs to be changed so that the KCP CR can still be used to recreate the SKR CR but that it is not overwritten from the SKR CR if it was changed by a customer. Instead it should always use the "virtual" module set that is fetched from both clusters.
- In case the virtual module set is not available (e.g. the remote cluster is not available) we can no longer retrieve the new desired state, thus producing a new short-circuit error: IF remote cluster cannot be reached, THEN error out the reconciliation and wait for requeue immediately

**Comment by adityabhatia** [comment]
What would happen if the Kyma in SKR is deleted? Since we do not persist it, do we:

- Start with a clean SKR Kyma CR? 
OR
- Persist SKR CR spec in KCP Kyma, say in .spec.skr.modules?

**Comment by jakobmoellersap** [comment]
If SKR is deleted we reuse spec from the KCP without persisting it in SKR, so basically it counts as a reset of Kyma
