### ISSUE TITLE
Prepare a template operator

### ISSUE THREAD

**Issue by adityabhatia** [kyma-project/kyma-operator#99]
A template operator is a re-usable operator which could be leveraged by component teams to create their own operators, to interact with the kyma-operator and thereby be a part of the modularisation framework

AC:
- [x] Prepare a template operator skeleton project
- [x] Implement a template CR managed by this operator 
- [x] Implement basic simple state handling for the template CR
- [x] Showcase operator best practices
- [x] Write documentation how to re-use this operator and inject into the kyma-operator

**Comment by jakobmoellersap** [comment]
Developer Notes:

- Base on existing v1alpha1 API Definition of Kyma / ModuleTemplate & Manifest
- Assume that CLI is used for Module Creation and Module Bundling in Reference Commands (e.g. Makefile in Skeleton Project)
- Make sure that Skeleton does not contain any project opinionation by using stub coding wherever necessary
- Assume that Skeleton is based on CRDs that at least implement the Operator State subresource with an Enum with the Same Value as Kyma status.state
